# Site settings
title: Sid Biswal Profile
description: Sid Biswal Profile
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sid Biswal
user_description: I am a data scientist and software developer
user_title: Co-Founder at REai/ PhD student at Georgia Tech
email: sid@reai.co
twitter_username: siddnitr1

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
